using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AngularApp1.Server.Migrations
{
    /// <inheritdoc />
    public partial class CreateCarLogsIfMissing : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Na niektórych środowiskach migracje mogły nie zostać faktycznie wykonane,
            // a backend oczekuje istnienia tabeli `car_logs`. Tworzymy ją warunkowo.
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS car_logs (
                    Id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                    CarId integer NOT NULL,
                    Username character varying(255) NOT NULL,
                    Action character varying(50) NOT NULL,
                    Timestamp timestamp with time zone NOT NULL,
                    CONSTRAINT PK_car_logs PRIMARY KEY (Id)
                );
            ");

            migrationBuilder.Sql(@"
                -- Uwaga: bez cudzysłowów Postgres zamienia identyfikator na lowercase.
                -- Dzięki temu indeks trafi w kolumnę `carid`, jeśli tabela powstała bez quoted identifiers.
                CREATE INDEX IF NOT EXISTS IX_car_logs_CarId
                ON car_logs (CarId);
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                DROP INDEX IF EXISTS ""IX_car_logs_CarId"";
            ");
            migrationBuilder.Sql(@"
                DROP TABLE IF EXISTS car_logs;
            ");
        }
    }
}
