using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AngularApp1.Server.Migrations
{
    
    public partial class CreateCarLogsIfMissing : Migration
    {
        
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS car_logs (
                    Id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                    CarId integer NOT NULL,
                    Username character varying(255) NOT NULL,
                    Action character varying(50) NOT NULL,
                    Timestamp timestamp with time zone NOT NULL,
                    CONSTRAINT PK_car_logs PRIMARY KEY (Id)
                );
            ");

            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS IX_car_logs_CarId
                ON car_logs (CarId);
            ");
        }

        
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                DROP INDEX IF EXISTS ""IX_car_logs_CarId"";
            ");
            migrationBuilder.Sql(@"
                DROP TABLE IF EXISTS car_logs;
            ");
        }
    }
}
